### PR TITLE
more things

### PR DESCRIPTION
**Pull request by RbCaVi**
move filenames to config
better !viewcog format
replace !eval with my code
revert token handling
recode lang.phraser() to be like assetload.getlocale()
replace evl() with cmdi[][]

### CODE REVIEW

**Comment by Sear-0887** [comment]
I don't understand why you want to replace evl() with a cmdi[][]. it is exactly created for replacing it.
If kept, it could add additional information handling (eg. languages depending on ctx.author). 
the local file will have 3 level (eventually), so the evl is used for compatibility.

**Comment by RbCaVi** [comment]
at least make it use arguments instead of one string

**Comment by RbCaVi** [comment]
i'll do that

**Comment by RbCaVi** [comment]
did

**Comment by RbCaVi** [comment]
i'll split the changes into several branches

**Comment by RbCaVi** [comment]
i have eval right now

**Pull request closed without merging**
